import { app, BrowserWindow, ipcMain } from "electron";
import { isProduction } from "./env";
import { join } from "path";
import Ffmpeg from "fluent-ffmpeg";
import { ffmpeg } from "./ffmpeg";

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

function initializeFfmpeg() {
  const resourcePath = isProduction()
    ? process.resourcesPath
    : join(__dirname, `../../resources/${process.platform}-${process.arch}`);
  Ffmpeg.setFfmpegPath(join(resourcePath, "ffmpeg"));
  Ffmpeg.setFfprobePath(join(resourcePath, "ffprobe"));
}

initializeFfmpeg();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require("electron-squirrel-startup")) {
  app.quit();
}

let stopCommand: (() => void) | null = null;

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 600,
    show: false, // Don't show until ready
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Show window when content is ready (eliminates white flash)
  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });

  ipcMain.on("ffmpeg-start", (event, pathIn: string) => {
    stopCommand = ffmpeg.start(
      pathIn,
      (progress) => {
        mainWindow.setProgressBar((progress.percent ?? 0) / 100);
        mainWindow.webContents.send("ffmpeg-progress", progress);
      },
      () => {
        mainWindow.setProgressBar(-1);
        mainWindow.webContents.send("ffmpeg-end", pathIn);
      },
      () => {
        mainWindow.setProgressBar(-1);
        mainWindow.webContents.send("ffmpeg-error", pathIn);
      },
    );
  });

  ipcMain.on("ffmpeg-stop", () => {
    stopCommand?.();
  });

  ipcMain.on("video-to-process-count", (_, count: number) => {
    app.dock?.setBadge(count ? `${count}` : "");
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  if (!isProduction()) {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
